/*
Copyright (c) 2019-2024 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dcore.math.base;

//version = UsePortableTrig;

enum double PI = 3.14159265358979323846;
enum double HALFPI = 1.5707964;
enum double QUARTPI = 0.7853982;
enum double INVPI = 0.31830988618;
enum double INVTWOPI = 0.1591549;
enum double TWOPI = 6.28318530718;
enum double THREEHALFPI = 4.7123889;

bool isNaN(real x) pure nothrow @nogc
{
    pragma(inline, true);
    return x != x;
}

int isInfinity(real x) pure nothrow @nogc
{
    pragma(inline, true);
    return !isNaN(x) && isNaN(x - x);
}

T max(T)(T a, T b) pure nothrow @nogc
{
    pragma(inline, true);
    return (a > b)? a : b;
}

T min(T)(T a, T b) pure nothrow @nogc
{
    pragma(inline, true);
    return (a < b)? a : b;
}

T abs(T)(T v) pure nothrow @nogc
{
    pragma(inline, true);
    return (v > 0.0)? v : -v;
}

T clamp(T)(T v, T mi, T ma) pure nothrow @nogc
{
    pragma(inline, true);
    if (v < mi) return mi;
    else if (v > ma) return ma;
    else return v;
}

bool isClose(real a, real b, real delta) pure nothrow @nogc
{
    pragma(inline, true);
    return abs(a - b) < delta;
}

real floor(real x) pure nothrow @nogc
{
    long intPart = cast(long)x;
    if (x < 0 && x != cast(real)intPart)
        return intPart - 1;
    return intPart;
}

real fmod(real x, real y) pure nothrow @nogc
{
    auto m = floor(x / y);
    return max(0, x - y * m);
}

version(FreeStanding)
{
    version = UsePortableTrig;
}

version(LDC)
{
    import ldc.intrinsics;
    alias sin = llvm_sin;
    alias cos = llvm_cos;
}
else
version(UsePortableTrig)
{
    import dcore.math.trigtables;
    
    real sin(real x) pure nothrow @nogc
    {
        pragma(inline, true);
        
        real xfmod = x - floor(x / TWOPI) * TWOPI;
        x = (0 > xfmod)? 0 : xfmod;
        
        real rsign = 1.0;
        real adjusted_x = x;
        if (x < 0) 
        {
            adjusted_x = -x;
            rsign = -1.0;
        }
        if (adjusted_x > PI) 
        {
            adjusted_x = min(PI, TWOPI - adjusted_x);
            rsign = -1.0;
        }
        
        real j = adjusted_x * ((sinfTable.length - 2) * INVPI);
        int zero = cast(int)j;
        real nx = j - zero;
        return ((1 - nx) * sinfTable[zero][0] + nx * sinfTable[zero + 1][0]) * rsign;
    }
    
    real cos(real x) pure nothrow @nogc
    {
        pragma(inline, true);
        
        real xfmod = x - floor(x / TWOPI) * TWOPI;
        x = (0 > xfmod)? 0 : xfmod;
        
        real adjusted_x = x;
        if (x < 0) 
        {
            adjusted_x = -x;
        }
        if (adjusted_x > PI) 
        {
            adjusted_x = min(PI, TWOPI - adjusted_x);
        }
        
        real j = adjusted_x * ((cosfTable.length - 2) * INVPI);
        int zero = cast(int)j;
        real nx = j - zero;
        return (1 - nx) * cosfTable[zero][0] + nx * cosfTable[zero + 1][0];
    }
}
else
version(NoPhobos)
{
    extern(C) nothrow @nogc
    {
        double sin(double x);
        double cos(double x);
        
        /*
        double ceil(double x);
        float ceilf(float x);
        real ceill(real x)
        {
            return ceil(x);
        }
        
        double floor(double x);
        float floorf(float x);
        real floorl(real x)
        {
            return floor(x);
        }
        */
    }
}
else
{
    import std.math;
    alias sin = std.math.sin;
    alias cos = std.math.cos;
}
