/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * In-place array sorting algorithms.
 * Very efficient for small-sized arrays.
 *
 * Copyright: Timur Gafarov 2026.
 * License: $(LINK2 boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dlib.container.sorting;

/**
 * Sorts the array in-place using selection sort algorithm and provided comparator function.
 * Comparator should accept two parameters (a, b) and return a boolean value:
 * true if a < b for sorting in ascending order, or true if a > b for sorting in descending order.
 */
T[] selectionSort(alias comparator, T)(T[] data)
{
    size_t len = data.length;
    size_t j;
    T tmp;
    
    size_t i = 0;
    while(i < len)
    {
        j = i;
        size_t k = i;
        while(k < len)
        {
            T a = data[j];
            T b = data[k];
            if (comparator(b, a))
                j = k;
            k += 1;
        }
        
        tmp = data[i];
        data[i] = data[j];
        data[j] = tmp;
        
        i += 1;
    }
    
    return data;
}

unittest
{
    int[] arr = [100, 50, 85, 10, 5, 99, 0];
    selectionSort!((a, b) => a < b)(arr);
    assert(arr[] == [0, 5, 10, 50, 85, 99, 100]);
}

/**
 * Sorts the array in-place using insertion sort algorithm and provided comparator function.
 * Comparator should accept two parameters (a, b) and return a boolean value:
 * true if a < b for sorting in ascending order, or true if a > b for sorting in descending order.
 */
T[] insertionSort(alias comparator, T)(T[] data)
{
    const len = data.length;
    for (size_t i = 1; i < len; ++i)
    {
        T key = data[i];
        size_t j = i;
        while (j > 0 && comparator(key, data[j - 1]))
        {
            data[j] = data[j - 1];
            --j;
        }
        data[j] = key;
    }
    return data;
}

unittest
{
    int[] arr = [100, 50, 85, 10, 5, 99, 0];
    insertionSort!((a, b) => a < b)(arr);
    assert(arr[] == [0, 5, 10, 50, 85, 99, 100]);
}
