/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/*
 * Permuted congruential generator.
 * The module provides both 32 and 64-bit versions.
 *
 * Description:
 * PCG is a family of non-cryptographic pseudo-random number generators
 * that have better statistical properties than the Mersenne Twister.
 * They are also faster and require much less memory.
 *
 * Copyright: Timur Gafarov 2026. Based on pcg-c by Melissa O'Neill.
 * License: $(LINK2 boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dlib.random.pcg;

///
enum PCG32
{
    Multiplier = 747796405U,
    Increment = 2891336453U
}

///
enum PCG64
{
    Multiplier = 6364136223846793005UL,
    Increment = 1442695040888963407UL
}

private __gshared ulong state64;
private __gshared uint state32;

/// Initializes the PCG state with the given seed values.
void init(ulong initialState64, uint initialState32)
{
    state64 = initialState64;
    pcg64();
    
    state32 = initialState32;
    pcg32();
}

/*
 * 64-bit PCG.
 * Based on pcg_oneseq_64_step_r and pcg_output_rxs_m_xs_64_64
 * from https://github.com/imneme/pcg-c/
 */
ulong pcg64()
{
    state64 = state64 * PCG64.Multiplier + PCG64.Increment;
    ulong lword = ((state64 >> ((state64 >> 59U) + 5U)) ^ state64) * 12605985483714917081UL;
    return (lword >> 43U) ^ lword;
}

/*
 * 32-bit PCG.
 * Based on pcg_oneseq_32_step_r and pcg_output_rxs_m_xs_32_32
 * from https://github.com/imneme/pcg-c/
 */
uint pcg32()
{
    state32 = state32 * PCG32.Multiplier + PCG32.Increment;
    uint word = ((state32 >> ((state32 >> 28U) + 4U)) ^ state32) * 277803737U;
    return (word >> 22U) ^ word;
}

/// Default PCG (32-bit).
alias pcg = pcg32;
