/*
Copyright (c) 2016 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Copyright: Eugene Wissner 2016-.
 * License: $(LINK2 boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Eugene Wissner
 */
module dlib.async.event.kqueue;

version (OSX)
{
    version = MacBSD;
    import core.sys.darwin.sys.event;
}
else version (iOS)
{
    version = MacBSD;
    import core.sys.darwin.sys.event;
}
else version (FreeBSD)
{
    version = MacBSD;
    import core.sys.freebsd.sys.event;
}
else version (OpenBSD)
{
    version = MacBSD;
    import core.sys.freebsd.sys.event;
}
else version (DragonFlyBSD)
{
    version = MacBSD;
    import core.sys.freebsd.sys.event;
}

version (MacBSD):

import dlib.async.event.selector;
import dlib.async.loop;
import dlib.async.watcher;
import core.sys.posix.unistd;
import dlib.memory;
import dlib.memory.mmappool;

class KqueueLoop : SelectorLoop
{
    private int fd;
    private kevent_t[] events;

    this()
    {
        super();

        if ((fd = kqueue()) == -1)
        {
            throw MmapPool.instance.make!BadLoopException("epoll initialization failed");
        }
        events = makeArray!kevent_t(defaultAllocator, maxEvents);
    }

    /**
     * Free loop internals.
     */
    ~this()
    {
        close(fd);
    }

    /**
     * Should be called if the backend configuration changes.
     *
     * Params:
     *     watcher   = Watcher.
     *     oldEvents = The events were already set.
     *     events    = The events should be set.
     *
     * Returns: $(D_KEYWORD true) if the operation was successful.
     */
    override protected bool reify(ConnectionWatcher watcher,
	                              EventMask oldEvents,
	                              EventMask events)
    {
        kevent_t event;

        if (events == oldEvents)
        {
            return true;
        }
        short kevents = (events & (Event.read | Event.accept) ? EVFILT_READ : 0)
                    | (events & Event.write ? EVFILT_WRITE : 0);

        if (events && !oldEvents)
        {
            EV_SET(&event, cast(ulong) watcher.socket.handle, kevents, EV_ADD | EV_ENABLE, 0U, 0L, null);
        }
        else if (events && !oldEvents)
        {
            EV_SET(&event, cast(ulong) watcher.socket.handle, kevents, EV_DELETE, 0U, 0L, null);
        }
        return true;
    }

    /**
     * Does the actual polling.
     */
    protected override void poll()
    {
    }
}
