/*
Copyright (c) 2015-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dlib.image.io.jpeg.baseline;

import std.stdio;
import std.format;

import dlib.core.bitio;
import dlib.core.stream;
import dlib.core.compound;
import dlib.image.color;
import dlib.image.image;
import dlib.image.io.jpeg.image;
import dlib.image.io.jpeg.bitstream;
import dlib.image.io.jpeg.mcu;
import dlib.image.io.jpeg.dct;

/*
 *  Decodes compressed data and creates RGB image from it
 */
Compound!(SuperImage, string) decodeBaseline(
    JPEGImage* jpg,
    InputStream istrm,
    SuperImageFactory imgFac)
{
    SuperImage img = imgFac.createImage(jpg.frame.width, jpg.frame.height, 3, 8);

    MCU mcu;
    foreach(ci, ref c; jpg.frame.components)
    {
        if (ci == 0)
            mcu.createYBlocks(c.hSubsampling, c.vSubsampling);
        else if (ci == 1)
            mcu.createCbBlocks(c.hSubsampling, c.vSubsampling);
        else if (ci == 2)
            mcu.createCrBlocks(c.hSubsampling, c.vSubsampling);
    }

    Compound!(SuperImage, string) error(string errorMsg)
    {
        mcu.free();
        if (img)
        {
            img.free();
            img = null;
        }
        return compound(img, errorMsg);
    }

    // Decode DCT coefficient from bit buffer
    int decodeCoef(uint buffer, ubyte numBits)
    {
        bool positive = getBit(buffer, 0);

        int value = 0;
        foreach(j; 0..numBits)
        {
            bool bit = getBit(buffer, numBits-1-j);
            value = setBit(value, j, bit);
        }

        if (positive)
            return value;
        else
            return value - 2^^numBits + 1;
    }

    if (jpg.scan.componentsNum != 1 && jpg.scan.componentsNum != 3)
    {
        return error(format(
                "loadJPEG error: unsupported number of scan components: %s",
                jpg.scan.componentsNum));
    }

    // Store previous DC coefficients
    int[3] dcCoefPrev;

    if (jpg.dqt.length == 0)
        return error("loadJPEG error: no DQTs found");

    ScanBitStream sbs;
    sbs.endMarkerFound = false;
    sbs.bytesRead = 0;
    sbs.prevByte = 0x00;
    sbs.curByte = 0x00;
    sbs.istrm = istrm;
    sbs.readNextByte();

    uint numMCUsH = jpg.frame.width / mcu.width + ((jpg.frame.width % mcu.width) > 0);
    uint numMCUsV = jpg.frame.height / mcu.height + ((jpg.frame.height % mcu.height) > 0);

    // Read MCUs
    foreach(mcuY; 0..numMCUsV)
    foreach(mcuX; 0..numMCUsH)
    {
        // Read MCU for each channel
        foreach(ci, ref c; jpg.scan.components)
        {
            auto tableDC = jpg.getHuffmanTable(0, c.tableIdDC);
            auto tableAC = jpg.getHuffmanTable(1, c.tableIdAC);

            if (tableDC is null)
                return error("loadJPEG error: illegal DC table index in MCU component");
            if (tableAC is null)
                return error("loadJPEG error: illegal AC table index in MCU component");

            auto component = jpg.frame.components[ci];
            auto hblocks = component.hSubsampling;
            auto vblocks = component.vSubsampling;
            auto dqtTableId = component.dqtTableId;
            if (dqtTableId >= jpg.dqt.length)
                return error("loadJPEG error: illegal DQT table index in MCU component");

            // Read 8x8 blocks
            foreach(by; 0..vblocks)
            foreach(bx; 0..hblocks)
            {
                int[8*8] block;

                // Read DC coefficient
                ubyte dcDiffLen;
                auto res = sbs.decodeByte(tableDC.huffmanTree, &dcDiffLen);
                if (!res[0]) return error(res[1]);

                if (dcDiffLen > 0)
                {
                    uint dcBuffer = sbs.readBits(dcDiffLen);
                    dcCoefPrev[ci] += decodeCoef(dcBuffer, dcDiffLen);
                }

                block[0] = dcCoefPrev[ci];

                // Read AC coefficients
                {
                    uint i = 1;
                    bool eob = false;
                    while (!eob && i < 64)
                    {
                        ubyte code;
                        res = sbs.decodeByte(tableAC.huffmanTree, &code);
                        if (!res[0]) return error(res[1]);

                        if (code == 0x00) // EOB, all next values are zero
                            eob = true;
                        else if (code == 0xF0) // ZRL, next 16 values are zero
                        {
                            foreach(j; 0..16)
                            if (i < 64)
                            {
                                block[i] = 0;
                                i++;
                            }
                        }
                        else
                        {
                            ubyte hi = hiNibble(code);
                            ubyte lo = loNibble(code);

                            uint zeroes = hi;
                            foreach(j; 0..zeroes)
                            if (i < 64)
                            {
                                block[i] = 0;
                                i++;
                            }

                            int acCoef = 0;
                            if (lo > 0)
                            {
                                uint acBuffer = sbs.readBits(lo);
                                acCoef = decodeCoef(acBuffer, lo);
                            }

                            if (i < 64)
                                block[i] = acCoef;

                            i++;
                        }
                    }
                }

                // Multiply block by quantization matrix
                foreach(i, ref v; block)
                    v *= jpg.dqt[dqtTableId].table[i];

                // Convert matrix from zig-zag order to normal order
                int[8*8] dctMatrix;

                foreach(i, v; block)
                    dctMatrix[dezigzag[i]] = v;

                idct64(dctMatrix.ptr);

                // Copy the matrix into corresponding channel
                int* outMatrixPtr;
                if (ci == 0)
                    outMatrixPtr = mcu.yBlocks[by * hblocks + bx].ptr;
                else if (ci == 1)
                    outMatrixPtr = mcu.cbBlocks[by * hblocks + bx].ptr;
                else if (ci == 2)
                    outMatrixPtr = mcu.crBlocks[by * hblocks + bx].ptr;
                else
                    return error("loadJPEG error: illegal component index");

                for(uint i = 0; i < 64; i++)
                    outMatrixPtr[i] = dctMatrix[i];
            }
        }

        // Convert MCU from YCbCr to RGB
        foreach(y; 0..mcu.height) // Pixel coordinates in MCU
        foreach(x; 0..mcu.width)
        {
            Color4f col = mcu.getPixel(x, y, jpg.scan.componentsNum == 1);

            // Pixel coordinates in image
            uint ix = mcuX * mcu.width + x;
            uint iy = mcuY * mcu.height + y;

            if (ix < img.width && iy < img.height)
                img[ix, iy] = col;
        }
    }

    version(JPEGDebug)
    {
        writefln("Bytes read: %s", sbs.bytesRead);
    }

    mcu.free();

    return compound(img, "");
}
