/*
Copyright (c) 2015-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dlib.image.io.jpeg.image;

import dlib.core.memory;
import dlib.container.array;
import dlib.image.io.jpeg.huffman;

struct JPEGImage
{
    struct JFIF
    {
        ubyte versionMajor;
        ubyte versionMinor;
        ubyte units;
        ushort xDensity;
        ushort yDensity;
        ubyte thumbnailWidth;
        ubyte thumbnailHeight;
        ubyte[] thumbnail;

        void free()
        {
            if (thumbnail.length)
                Delete(thumbnail);
        }
    }

    struct DQT
    {
        ubyte precision;
        ubyte tableId;
        ubyte[] table;

        void free()
        {
            if (table.length)
                Delete(table);
        }
    }

    struct FrameComponent
    {
        ubyte id;
        ubyte hSubsampling;
        ubyte vSubsampling;
        ubyte dqtTableId;
    }

    struct Frame
    {
        ubyte precision;
        ushort height;
        ushort width;
        ubyte componentsNum;
        FrameComponent[] components;
        bool isProgressive;

        void free()
        {
            if (components.length)
                Delete(components);
        }
    }

    struct DHT
    {
        ubyte clas;
        ubyte tableId;
        Array!HuffmanTableEntry huffmanTable;
        HuffmanTreeNode* huffmanTree;

        void free()
        {
            huffmanTree.free();
            Delete(huffmanTree);
            huffmanTable.free();
        }
    }

    struct ScanComponent
    {
        ubyte tableIdDC;
        ubyte tableIdAC;
        ubyte id;
        ubyte _padding;
    }

    struct Scan
    {
        ubyte componentsNum;
        ScanComponent[] components;
        ubyte spectralSelectionStart;
        ubyte spectralSelectionEnd;
        ubyte successiveApproximationBitHigh;
        ubyte successiveApproximationBitLow;

        void free()
        {
            if (components.length)
                Delete(components);
        }
    }

    JFIF jfif;
    DQT[] dqt;
    Frame frame;
    DHT[] dht;
    Scan scan;
    ushort restartInterval;

    DQT* addDQT()
    {
        if (dqt.length > 0)
            reallocateArray(dqt, dqt.length+1);
        else
            dqt = New!(DQT[])(1);
        return &dqt[$-1];
    }

    DHT* addDHT()
    {
        if (dht.length > 0)
            reallocateArray(dht, dht.length+1);
        else
            dht = New!(DHT[])(1);
        return &dht[$-1];
    }

    void free()
    {
        jfif.free();
        foreach(ref t; dqt) t.free();
        if (dqt.length)
            Delete(dqt);
        frame.free();
        foreach(ref t; dht) t.free();
        if (dht.length)
            Delete(dht);
        scan.free();
    }

    DQT* getQuantizationTable(ubyte id)
    {
        foreach_reverse(ref t; dqt)
            if (t.tableId == id)
                return &t;
        return null;
    }

    DHT* getHuffmanTable(ubyte clas, ubyte id)
    {
        foreach_reverse(ref t; dht)
            if (t.clas == clas &&
                t.tableId == id)
                return &t;
        return null;
    }
}
