/*
Copyright (c) 2016 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dlib.image.transform;

import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.affine;
import dlib.math.utils;

import dlib.image.image;
import dlib.image.color;

/*
 * Rotates an image clockwise around its center.
 * angle is in degrees.
 */
SuperImage rotateAroundCenter(SuperImage img, float angle)
{
    return rotateAroundCenter(img, null, angle);
}
 
SuperImage rotateAroundCenter(SuperImage img, SuperImage outp, float angle)
{
    SuperImage res;
    if (outp)
        res = outp;
    else
        res = img.createSameFormat(img.width, img.height);

    Vector2f center = Vector2f(res.width, res.height) * 0.5f;
    Matrix2x2f m = rotation2D(degtorad(angle));
    foreach(y; 0..res.height)
    foreach(x; 0..res.width)
    {
        Vector2f v1 = (Vector2f(x, y) - center) * m + center;
        res[x, y] = bilinearPixel(img, v1.x, v1.y);
    }

    return res;
}

// TODO: translate image
// TODO: scale image
// TODO: transform image by affine matrix
