name: CI

on: 
  push:
    branches: [ master ]
    paths:
    - 'dlib/**'
    - 'dub.json'
    - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'dlib/**'
    - 'dub.json'
    - '.github/workflows/**'

jobs:
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: dub test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - name: Run tests with coverage
        run: dub test --build=unittest-cov
      - name: Run code coverage
        run: dub run doveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
